server:
  port: 21204
  servlet:
    context-path: /

sysinit:
  jdbc:
    url: 3111111111111
    username: 222222222222222222222
    password: 111111111
    driver: 1111111


spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 3
      auto-commit: true
      idle-timeout: 10000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    master:
      username: root
      password: RuXocrvFg1#E
      jdbc-url: jdbc:mysql://192.168.1.122/yyf_sss_goods?useSSL=FALSE&serverTimezone=UTC&allowMultiQueries=true
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      username: root
      password: RuXocrvFg1#E
      jdbc-url: jdbc:mysql://192.168.1.122/yyf_sss_goods?useSSL=FALSE&serverTimezone=UTC&allowMultiQueries=true
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
   database: 0
   host: 192.168.1.123
   port: 6379
   password: yyf123456
   timeout: 10000
   pool:
     max-active: 8
     max-wait: 800
     max-idle: 8
     min-idle: 2

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.124:8380/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 4